### ISSUE TITLE
sqlite performance improvements 

### ISSUE THREAD

**Issue by mtijanic** [mtijanic/nwccc#18]
Stale manifest cleanup is slow because of the index updates (probably). Investigate using WAL and disabling fsyncs and whatever else to speed it up a bit. Data loss is not s huge concern, you can always nuke the db and start again.

**Comment by niv** [comment]
Tested w/ index - about a third faster on my dumb testcase than without. Still not very fast, but fast enough that I didn't get impatient wondering if it crashed waiting for the next log message.
